export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING'
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT'
