export const  CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const  CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'
export const  CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'

// export const  ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
// export const  ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
// export const  ORDER_DETAIL_ERROR = 'ORDER_DETAIL_ERROR'

// export const  ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
// export const  ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
// export const  ORDER_PAY_ERROR = 'ORDER_PAY_ERROR'

export const  ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const  ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const  ORDER_DELETE_ERROR = 'ORDER_DELETE_ERROR'

// export const  MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST'
// export const  MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS'
// export const  MY_ORDER_LIST_ERROR = 'MY_ORDER_LIST_ERROR'

export const  ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const  ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const  ORDER_LIST_ERROR = 'ORDER_LIST_ERROR'
