export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR'
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'

export const PRODUCT_DETAIL_ERROR = 'PRODUCT_DETAIL_ERROR'
export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'

export const PRODUCT_SAVE_ERROR = 'PRODUCT_SAVE_ERROR'
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS'
export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST'

export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'

export const SAVE_PRODUCT_REVIEW_REQUEST = 'SAVE_PRODUCT_REVIEW_REQUEST'
export const SAVE_PRODUCT_REVIEW_SUCCESS = 'SAVE_PRODUCT_REVIEW_SUCCESS'
export const SAVE_PRODUCT_REVIEW_ERROR = 'SAVE_PRODUCT_REVIEW_ERROR'
export const SAVE_PRODUCT_REVIEW_RESET = 'SAVE_PRODUCT_REVIEW_RESET'

export const PRODUCT_GET_COLORS_REQUEST = 'PRODUCT_GET_COLORS_REQUEST'
export const PRODUCT_GET_COLORS_SUCCESS = 'PRODUCT_GET_COLORS_SUCCESS'
export const PRODUCT_GET_COLORS_ERROR = 'PRODUCT_GET_COLORS_ERROR'
export const PRODUCT_GET_SIZES_REQUEST = 'PRODUCT_GET_SIZES_REQUEST'
export const PRODUCT_GET_SIZES_SUCCESS = 'PRODUCT_GET_SIZES_SUCCESS'
export const PRODUCT_GET_SIZES_ERROR = 'PRODUCT_GET_SIZES_ERROR'




